"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
[](bg:peach fg:red)\
$username\
[](bg:yellow fg:peach)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$nodejs\
$java\
$python\
$lua\
[](fg:blue bg:surface1)\
$package\
[](fg:surface1 bg:surface0)\
$time\
[ ](fg:surface0)\
$line_break$character"""

command_timeout = 1000

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:red fg:base"

[os.symbols]
Windows = "   "

[username]
show_always = true
style_user = "bg:peach fg:base"
style_root = "bg:peach fg:base"
format = '[ $user ]($style)'

[directory]
style = "bold fg:base bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bold bg:green"
format = '[[ $symbol $branch ](bold fg:base bg:green)]($style)'

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "!${count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "\\$${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
style = "bold bg:green"
format = '[[($all_status$ahead_behind )](bold fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[lua]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[java]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $context) ](fg:subtext1 bg:surface1)]($style)'

[package]
symbol = ""
display_private = true
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:subtext1 bg:surface1)]($style)'

[time]
disabled = false
time_format = "%R %d/%m/%y"
style = "bg:surface0"
format = '[[   $time ](fg:subtext0 bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ λ](bold fg:green)'
error_symbol = '[ λ](bold fg:red)'
vimcmd_symbol = '[ λ](bold fg:green)'
vimcmd_replace_one_symbol = '[ λ](bold fg:mauve)'
vimcmd_replace_symbol = '[ λ](bold fg:mauve)'
vimcmd_visual_symbol = '[ λ](bold fg:yellow)'
